version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && gunicorn --bind 127.0.0.1:8000 sitechecker.wsgi"
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A sitechecker worker -l info
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A sitechecker beat -l info
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.2
    environment:
        - POSTGRES_PASSWORD=8149547570
        - POSTGRES_USER=postgres
        - POSTGRES_DB=sitechecker
    restart: on-failure

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - '6379:6379'
