# Generated by Django 3.0.6 on 2020-06-07 08:20
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    replaces = [
        ("checkerapp", "0001_initial"),
        ("checkerapp", "0002_auto_20200509_1754"),
        ("checkerapp", "0003_auto_20200515_1049"),
        ("checkerapp", "0004_report"),
        ("checkerapp", "0005_auto_20200517_1908"),
        ("checkerapp", "0006_pinginfo_status"),
        ("checkerapp", "0007_sitelist_failure_count"),
        ("checkerapp", "0008_auto_20200521_0813"),
        ("checkerapp", "0009_sitelist_maintenance_mode"),
        ("checkerapp", "0010_sitelist_alert_type"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_celery_results", "0007_remove_taskresult_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=30, unique=True)),
                ("interval", models.CharField(max_length=10)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sitelist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="sitelist_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("failure_count", models.IntegerField(default=1)),
                ("maintenance_mode", models.IntegerField(default=0)),
                ("alert_type", models.CharField(default="email", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="PingInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checkerapp.SiteList",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("UP", "UP"), ("DOWN", "DOWN")],
                        default=1,
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
