# Generated by Django 3.0.6 on 2020-06-14 13:45
import django.db.models.deletion
import jsonfield.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interval", models.IntegerField()),
                ("backoff_count", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "severe_level",
                    models.SmallIntegerField(
                        choices=[(0, "NORMAL"), (1, "WARNING"), (2, "CRITICAL")],
                        default=0,
                    ),
                ),
                (
                    "alert_type",
                    models.SmallIntegerField(
                        choices=[(0, "EMAIL"), (1, "WHATSAPP"), (2, "SLACK")], default=0
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("object_id", models.CharField(max_length=50)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commoninfo_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CheckResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.SmallIntegerField(choices=[(1, "SUCCESS"), (0, "FAILURE")]),
                ),
                ("metadata", jsonfield.fields.JSONField()),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TcpCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("results", models.ManyToManyField(to="checkerapp.CheckResult")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("checks", models.ManyToManyField(to="checkerapp.BaseCheck")),
            ],
        ),
        migrations.CreateModel(
            name="PingCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("results", models.ManyToManyField(to="checkerapp.CheckResult")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="HttpCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=50, unique=True)),
                ("expected_status_code", models.IntegerField()),
                ("results", models.ManyToManyField(to="checkerapp.CheckResult")),
            ],
            options={"abstract": False},
        ),
    ]
