# Generated by Django 3.0.6 on 2020-06-14 14:02
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0001_initial")]

    operations = [migrations.RemoveField(model_name="checkresult", name="metadata")]
