# Generated by Django 3.0.6 on 2020-06-07 14:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0001_squashed_0010_sitelist_alert_type")]

    operations = [
        migrations.AlterField(
            model_name="pinginfo",
            name="status",
            field=models.SmallIntegerField(choices=[(1, "UP"), (0, "DOWN")]),
        ),
        migrations.AlterField(
            model_name="sitelist", name="failure_count", field=models.IntegerField()
        ),
    ]
