# Generated by Django 3.0.6 on 2020-05-15 16:40
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_results", "0007_remove_taskresult_hidden"),
        ("checkerapp", "0003_auto_20200515_1049"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_results.TaskResult",
                    ),
                ),
            ],
        )
    ]
