# Generated by Django 3.0.6 on 2020-06-20 10:03
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0003_auto_20200616_1431")]

    operations = [
        migrations.AlterField(
            model_name="checkresult",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
