# Generated by Django 3.0.6 on 2020-06-23 15:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0004_auto_20200620_1003")]

    operations = [
        migrations.AddField(
            model_name="tcpcheck", name="port", field=models.IntegerField(default=443)
        )
    ]
