# Generated by Django 3.0.6 on 2020-06-27 15:43
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0007_auto_20200626_0645")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="httpcheck",
            name="site_name",
            field=models.CharField(default="https://", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
