# Generated by Django 3.0.6 on 2020-05-21 08:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0007_sitelist_failure_count")]

    operations = [
        migrations.AlterField(
            model_name="sitelist",
            name="interval",
            field=models.CharField(max_length=10),
        )
    ]
