# Generated by Django 3.0.6 on 2020-07-01 06:59
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0009_auto_20200701_0637")]

    operations = [
        migrations.RenameField(
            model_name="alertsent", old_name="check_id", new_name="check_obj"
        )
    ]
