# Generated by Django 3.0.6 on 2020-07-05 11:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0012_alertplugin_alertpluginuserdata")]

    operations = [
        migrations.RemoveField(model_name="alertpluginuserdata", name="check_obj"),
        migrations.AddField(
            model_name="alertpluginuserdata",
            name="check_obj",
            field=models.ManyToManyField(
                related_name="plugin_users", to="checkerapp.BaseCheck"
            ),
        ),
        migrations.AlterField(
            model_name="basecheck",
            name="alert_type",
            field=models.SmallIntegerField(
                choices=[
                    (0, "EMAIL"),
                    (1, "TELEGRAM"),
                    (2, "SMS"),
                    (3, "NEW_TELEGRAM"),
                ],
                default=0,
            ),
        ),
    ]
