# Generated by Django 3.0.6 on 2020-07-05 11:45
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0013_auto_20200705_1128")]

    operations = [
        migrations.RemoveField(model_name="alertpluginuserdata", name="sent_at")
    ]
