# Generated by Django 3.0.6 on 2020-07-06 09:49
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checkerapp", "0014_remove_alertpluginuserdata_sent_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="alertplugin", name="enabled"),
        migrations.RemoveField(model_name="alertplugin", name="title"),
        migrations.AddField(
            model_name="alertplugin",
            name="alert_receiver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_receiver",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alertplugin",
            name="check_obj",
            field=models.ManyToManyField(
                related_name="plugin_users", to="checkerapp.BaseCheck"
            ),
        ),
        migrations.DeleteModel(name="AlertPluginUserData"),
    ]
