# Generated by Django 3.0.6 on 2020-07-07 04:29
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0015_auto_20200706_0949")]

    operations = [migrations.RemoveField(model_name="alertplugin", name="check_obj")]
