# Generated by Django 3.0.6 on 2020-07-09 07:05
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checkerapp", "0018_remove_basecheck_alert_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="users",
            field=models.ManyToManyField(
                related_name="service_users", to=settings.AUTH_USER_MODEL
            ),
        )
    ]
