# Generated by Django 3.0.6 on 2020-07-09 13:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0019_service_users")]

    operations = [migrations.RemoveField(model_name="basecheck", name="users")]
