# Generated by Django 3.0.6 on 2020-07-09 13:59
from django.db import migrations

# from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0020_remove_basecheck_users")]

    operations = [
        migrations.RemoveField(model_name="profile", name="telegram_id"),
        # migrations.AddField(
        #     model_name='service',
        #     name='plugins',
        #     field=models.CharField(choices=[], default='GenericAlertPlugin', max_length=50),
        #     preserve_default=False,
        # ),
    ]
