# Generated by Django 3.0.6 on 2020-07-10 14:13
import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0021_auto_20200709_1359")]

    operations = [
        migrations.AddField(
            model_name="service",
            name="critical_severity",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(default=list), default=[3, 1], size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="warning_severity",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(default=list), default=[0, 1], size=None
            ),
            preserve_default=False,
        ),
    ]
