# Generated by Django 3.0.6 on 2020-07-11 06:26
import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0022_auto_20200710_1413")]

    operations = [
        migrations.CreateModel(
            name="PluginList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("active_status", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="service",
            name="critical_severity",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(default=0), size=None
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="warning_severity",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(default=0), size=None
            ),
        ),
    ]
