# Generated by Django 3.0.6 on 2020-07-11 07:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0023_auto_20200711_0626")]

    operations = [
        migrations.RemoveField(model_name="service", name="critical_severity"),
        migrations.RemoveField(model_name="service", name="warning_severity"),
        migrations.AddField(
            model_name="service",
            name="warning_severity",
            field=models.ManyToManyField(
                related_name="plugin_list", to="checkerapp.PluginList"
            ),
        ),
    ]
