# Generated by Django 3.0.6 on 2020-07-11 09:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0024_auto_20200711_0714")]

    operations = [
        migrations.AddField(
            model_name="service",
            name="critical_severity",
            field=models.ManyToManyField(
                related_name="critical_plugin_list", to="checkerapp.PluginList"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="warning_severity",
            field=models.ManyToManyField(
                related_name="warnign_plugin_list", to="checkerapp.PluginList"
            ),
        ),
    ]
