# Generated by Django 3.0.6 on 2020-07-11 18:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0025_auto_20200711_0907")]

    operations = [
        migrations.CreateModel(
            name="TempPlugin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plugin_temp", models.ManyToManyField(to="checkerapp.AlertPlugin")),
            ],
        )
    ]
