# Generated by Django 3.0.6 on 2020-07-12 08:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0026_tempplugin")]

    operations = [
        migrations.AddField(
            model_name="alertplugin",
            name="custom_plugin",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(name="TempPlugin"),
    ]
