# Generated by Django 3.0.6 on 2020-07-12 08:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0027_auto_20200712_0829")]

    operations = [
        migrations.RemoveField(model_name="alertplugin", name="custom_plugin"),
        migrations.AddField(
            model_name="pluginlist",
            name="custom_plugin",
            field=models.BooleanField(default=True),
        ),
    ]
