# Generated by Django 3.0.6 on 2020-07-12 11:53
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0028_auto_20200712_0831")]

    operations = [migrations.DeleteModel(name="Profile")]
