# Generated by Django 3.0.6 on 2020-07-12 13:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0029_delete_profile")]

    operations = [migrations.RemoveField(model_name="pluginlist", name="custom_plugin")]
