# Generated by Django 3.0.6 on 2020-07-12 15:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("checkerapp", "0030_remove_pluginlist_custom_plugin")]

    operations = [
        migrations.AlterField(
            model_name="basecheck",
            name="severe_level",
            field=models.SmallIntegerField(
                choices=[(0, "WARNING"), (1, "CRITICAL")], default=0
            ),
        )
    ]
