"""
Django settings for sitechecker project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import os
from distutils import strtobool

from django.core.exceptions import ImproperlyConfigured

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def get_bool_from_env(name, default_value):
    if name in os.environ:
        value = os.getenv(name)
        try:
            return bool(strtobool(value))
        except ValueError as e:
            error_msg = "{} is an invalid value for {}".format(value, name)
            raise ImproperlyConfigured(error_msg) from e
    return default_value


def get_env_variable_or_default(name, default_value):
    if name not in os.environ:
        return default_value
    return (os.getenv(name),)


def get_env_variable(var_name):
    try:
        return (os.getenv(var_name),)
    except KeyError:
        error_msg = "Set the %s environment variable" % var_name
        raise ImproperlyConfigured(error_msg)


# SECRET_KEY = (os.getenv("DJANGO_SECRET_KEY"),)
SECRET_KEY = get_env_variable("DJANGO_SECRET_KEY")

DEBUG = get_bool_from_env("DEBUG", True)

ALLOWED_HOSTS = []


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Custom
    "accounts",
    "checkerapp",
    # Third-party
    "celery",
    "widget_tweaks",
    "django_extensions",
    # Plugins
    "sc_generic_plugin",
    "django_telegrambot",  # required for telegram_bot
    "bot",
    # test plugins
    "sc_sms_plugin",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sitechecker.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

# DATABASES = {
#     "default": {
#         "ENGINE": os.getenv("SQL_ENGINE", "django.db.backends.postgresql"),
#         "NAME": os.getenv("SQL_DATABASE", "sitechecker"),
#         "USER": os.getenv("SQL_USER", "postgres"),
#         "PASSWORD": os.getenv("SQL_PASSWORD"),
#         "HOST": os.getenv("SQL_HOST", "localhost"),
#         "PORT": os.getenv("SQL_PORT"),
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": get_env_variable_or_default(
            "SQL_ENGINE", "django.db.backends.postgresql"
        ),
        "NAME": get_env_variable_or_default("SQL_DATABASE", "sitechecker"),
        "USER": get_env_variable_or_default("SQL_USER", "postgres"),
        "PASSWORD": get_env_variable("SQL_PASSWORD"),
        "HOST": get_env_variable_or_default("SQL_HOST", "localhost"),
        "PORT": get_env_variable_or_default("SQL_PORT", "5432"),
    }
}

WSGI_APPLICATION = "sitechecker.wsgi.application"


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGOUT_REDIRECT_URL = "checkerapp:home"
LOGIN_REDIRECT_URL = "checkerapp:home"
LOGIN_URL = "/login"

STATIC_URL = "/static/"

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# EMAIL stuff
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = ""
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

# Celery
BROKER_URL = get_env_variable_or_default("REDIS_HOST", "redis://127.0.0.1:6379/0")
CELERY_REDIS_PORT = 6379
CELERY_REDIS_DB = 0

# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_CACHE_BACKEND = 'django-cache'
CELERY_ACCEPT_CONTENT = ["pickle"]
CELERY_RESULT_SERIALIZER = "pickle"
CELERY_TASK_SERIALIZER = "pickle"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(levelname)s %(asctime)s %(module)s %(message)s"},
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "loggers": {"": {"handlers": ["console"], "level": "INFO", "propagate": True}},
}


DJANGO_TELEGRAMBOT = {
    "MODE": "POLLING",
    "BOTS": [
        {
            "TOKEN": get_env_variable_or_default(
                "TG_BOT_TOKEN", "***REMOVED***"
            )
        }
    ],
}
