# Generated by Django 3.0.6 on 2020-05-09 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitelist",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sitelist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
