# Generated by Django 3.0.6 on 2020-05-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.SiteList')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
