# Generated by Django 3.0.6 on 2020-05-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0007_sitelist_failure_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitelist",
            name="interval",
            field=models.CharField(max_length=10),
        ),
    ]
